
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jennifer Vaughn
 */
public class currencyConverter extends javax.swing.JFrame {

    /**
     * Creates new form currencyConverter
     */
    public currencyConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        formAmount = new javax.swing.JTextField();
        formFrom = new javax.swing.JComboBox<>();
        formTo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Currency Converter");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Enter the Amount");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("To");

        formAmount.setBackground(new java.awt.Color(204, 204, 204));

        formFrom.setBackground(new java.awt.Color(204, 204, 204));
        formFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "Euro", "Yen", "Mexican Peso" }));
        formFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formFromActionPerformed(evt);
            }
        });

        formTo.setBackground(new java.awt.Color(204, 204, 204));
        formTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "Euro", "Yen", "Mexican Peso" }));

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formAmount)
                            .addComponent(formFrom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formTo, 0, 192, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(formAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(formFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(formTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Double result;
        Double amount = Double.parseDouble(formAmount.getText());
        
        //USD to Euro
        if(formFrom.getSelectedItem().toString() == "USD" && formTo.getSelectedItem().toString() == "Euro"){
            result = amount * 0.96;
            JOptionPane.showMessageDialog(this, "Your converted amount is " + result.toString());
        }
        //USD to Yen
        if(formFrom.getSelectedItem().toString() == "USD" && formTo.getSelectedItem().toString() == "Yen"){
            result = amount * 138.82;
            JOptionPane.showMessageDialog(this, "Your converted amount is " + result.toString());
        }
        //USD to Peso
        if(formFrom.getSelectedItem().toString() == "USD" && formTo.getSelectedItem().toString() == "Mexican Peso"){
            result = amount * 19.51;
            JOptionPane.showMessageDialog(this, "Your converted amount is $" + result.toString());
        }
        
        //Euro to USD
        if(formFrom.getSelectedItem().toString() == "Euro" && formTo.getSelectedItem().toString() == "USD"){
            result = amount * 1.04;
            JOptionPane.showMessageDialog(this, "Your converted amount is $" + result.toString());
        }
        //Euro to Yen
        if(formFrom.getSelectedItem().toString() == "Euro" && formTo.getSelectedItem().toString() == "Yen"){
            result = amount * 143.98;
            JOptionPane.showMessageDialog(this, "Your converted amount is " + result.toString());
        }
        //Euro to Peso
        if(formFrom.getSelectedItem().toString() == "Euro" && formTo.getSelectedItem().toString() == "Mexican Peso"){
            result = amount * 20.20;
            JOptionPane.showMessageDialog(this, "Your converted amount is $" + result.toString());
        }
        
        //Yen to USD
        if(formFrom.getSelectedItem().toString() == "Yen" && formTo.getSelectedItem().toString() == "USD"){
            result = amount * 0.0072;
            JOptionPane.showMessageDialog(this, "Your converted amount is $" + result.toString());
        }
        //Yen to Euro
        if(formFrom.getSelectedItem().toString() == "Yen" && formTo.getSelectedItem().toString() == "Euro"){
            result = amount * 0.0069;
            JOptionPane.showMessageDialog(this, "Your converted amount is " + result.toString());
        }
        //Yen to Peso
        if(formFrom.getSelectedItem().toString() == "Yen" && formTo.getSelectedItem().toString() == "Mexican Peso"){
            result = amount * 0.14;
            JOptionPane.showMessageDialog(this, "Your converted amount is $" + result.toString());
        }
        
        //Peso to USD
        if(formFrom.getSelectedItem().toString() == "Mexican Peso" && formTo.getSelectedItem().toString() == "USD"){
            result = amount * 0.051;
            JOptionPane.showMessageDialog(this, "Your converted amount is $" + result.toString());
        }
        //Peso to Euro
        if(formFrom.getSelectedItem().toString() == "Mexican Peso" && formTo.getSelectedItem().toString() == "Euro"){
            result = amount * 0.049;
            JOptionPane.showMessageDialog(this, "Your converted amount is " + result.toString());
        }
        //Peso to Yen
        if(formFrom.getSelectedItem().toString() == "Mexican Peso" && formTo.getSelectedItem().toString() == "Yen"){
            result = amount * 7.12;
            JOptionPane.showMessageDialog(this, "Your converted amount is " + result.toString());
        }
        
        
        //When they're the same...
        
        //USD
        if(formFrom.getSelectedItem().toString() == "USD" && formTo.getSelectedItem().toString() == "USD"){
            result = amount;
            JOptionPane.showMessageDialog(this, "Your 'From' and 'To' selections are identical. Your amount is $" + result.toString());
        }
        //Euro
        if(formFrom.getSelectedItem().toString() == "Euro" && formTo.getSelectedItem().toString() == "Euro"){
            result = amount;
            JOptionPane.showMessageDialog(this, "Your 'From' and 'To' selections are identical. Your amount is " + result.toString());
        }
        //Yen
        if(formFrom.getSelectedItem().toString() == "Yen" && formTo.getSelectedItem().toString() == "Yen"){
            result = amount;
            JOptionPane.showMessageDialog(this, "Your 'From' and 'To' selections are identical. Your amount is " + result.toString());
        }
        //Peso
        if(formFrom.getSelectedItem().toString() == "Mexican Peso" && formTo.getSelectedItem().toString() == "Mexican Peso"){
            result = amount;
            JOptionPane.showMessageDialog(this, "Your 'From' and 'To' selections are identical. Your amount is $" + result.toString());
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formFromActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField formAmount;
    private javax.swing.JComboBox<String> formFrom;
    private javax.swing.JComboBox<String> formTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
